//
//  MoviePresenter.swift
//  ToolboxApp
//
//  Created by Laura Sarmiento Almanza on 10/13/19.
//  Copyright (c) 2019 Laura Sarmiento Almanza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MoviePresenter {

    // MARK: - Private properties -

    private unowned let view: MovieViewInterface
    private let interactor: MovieInteractorInterface
    private let wireframe: MovieWireframeInterface

    // MARK: - Lifecycle -

    init(view: MovieViewInterface, interactor: MovieInteractorInterface, wireframe: MovieWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MoviePresenter: MoviePresenterInterface {
    func loadMovies() {
        let source = interactor.fetchMovies()
        view.drawMoviesData(source: source)
    }
    
    func selectMovieItem(_ item: Movie.Item) {
        if let videoUrl = item.videoUrl?.toUrl() {
            wireframe.openVideo(url: videoUrl)
        } else {
            wireframe.showErrorMessage("Video no disponible")
        }
    }
}
