//
//  MovieInterfaces.swift
//  ToolboxApp
//
//  Created by Laura Sarmiento Almanza on 10/13/19.
//  Copyright (c) 2019 Laura Sarmiento Almanza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift

protocol MovieWireframeInterface: WireframeInterface {
    func openVideo(url: URL)
    func showErrorMessage(_ message: String)
}

protocol MovieViewInterface: ViewInterface {
    func drawMoviesData(source: Observable<[Movie]>)
}

protocol MoviePresenterInterface: PresenterInterface {
    func loadMovies()
    func selectMovieItem(_ item: Movie.Item)
}

protocol MovieInteractorInterface: InteractorInterface {
    func fetchMovies() -> Observable<[Movie]>
}
