//
//  MovieInteractor.swift
//  ToolboxApp
//
//  Created by Laura Sarmiento Almanza on 10/13/19.
//  Copyright (c) 2019 Laura Sarmiento Almanza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class MovieInteractor {
    
    var apiService: ApiServicesType!
}

// MARK: - Extensions -

extension MovieInteractor: MovieInteractorInterface {
    
    func fetchMovies() -> Observable<[Movie]> {
        apiService.request(to: .movies)
            .mapArray(Movie.self)
    }
}
